# A python Number Guessing Game Program
""" Import random module with the randint function inorder to select a random number"""
import random

""" Defined the function guessing_game for our program"""
def guessing_game():
    print("I'm thinking of a number between 0 and 100")
    
    """ This line generates a random number"""
    num= random.randint(0, 100)

    """ Ask the user to guess a number"""
    guess = input("Try to guess a number:")
  
    """ In this while loop we are checking, while the guess is not equal to the number generated by the system"""
    while guess != str(num):
        """ Checks if the guess is numeric"""
        if guess.isnumeric():
            if int(guess) > int(num):
                print("Guess is Too High!")
                # guess = int("Enter a number betweeen 0 to 100")
            if int(guess) < int(num):
                print("Guess is Too Low!")
            guess = input("Try to guess a number:")
        else:
            """ Returns this when the guess is not numeric"""
            guess = input("Try to guess a number(Invalid Option given):")
    """ Print the guess is correct if it has met the conditions"""
    print('just right')  
guessing_game()
               